### ISSUE TITLE
like to add

### ISSUE THREAD

**Issue by xoceunder** [dinamic/bw#1]
@dinamic

like being able to add 2

echo json_encode(array(
    'label' => 'rx',
    'data' => array_values($_SESSION['rx'])
array(
    'label' => 'tx',
    'data' => array_values($_SESSION['tx']))

**Comment by dinamic** [comment]
Sorry, I didn't saw this issue. Is this still relevant request?

**Comment by dinamic** [comment]
ping @xoceunder

**Comment by dinamic** [comment]
Closing this as two years no response.
